// Azure Resource Graph Query
// Show Windows VM without AHB
resourcecontainers
| where type =~ 'Microsoft.Resources/subscriptions'
| where tostring (properties.subscriptionPolicies.quotaId) !has 'MSDNDevTest_2014-09-01'
| extend SubscriptionName=name
| join (
    resources
    | where type =~ 'microsoft.compute/virtualmachines' or type =~ 'microsoft.compute/virtualMachineScaleSets'
    | where tostring(properties.storageProfile.imageReference.publisher ) == 'MicrosoftWindowsServer' or tostring(properties.virtualMachineProfile.storageProfile.osDisk.osType) == 'Windows' or tostring(properties.storageProfile.imageReference.publisher ) == 'microsoftsqlserver'
    | where tostring(properties.['licenseType']) !has 'Windows' and tostring(properties.virtualMachineProfile.['licenseType']) == 'Windows_Server'
    | extend WindowsId=id, VMSku=tostring(properties.hardwareProfile.vmSize), vmResourceGroup=resourceGroup, vmType=type, Location=location,LicenseType = tostring(properties.['licenseType'])
    | extend ActualCores = toint(extract('.[A-Z]([0-9]+)', 1, tostring(properties.hardwareProfile.vmSize)))
    | extend CheckAHBWindows = case(
        type == 'microsoft.compute/virtualmachines' or type =~ 'microsoft.compute/virtualMachineScaleSets', iif((properties.['licenseType'])
        !has 'Windows' and (properties.virtualMachineProfile.['licenseType']) !has 'Windows' , 'AHB-disabled', 'AHB-enabled'),
        'Not Windows'
    )
) on subscriptionId

