name: Zip on Merged PR

on:
  pull_request:
    types: [closed]

jobs:
  zip-job:
    if: ${{ github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'Dev' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Zip azure-resources directory
        run: |
          zip -r azure-resources.zip content/azure-resources
          ls -la

      - name: Upload zipped artifact
        uses: actions/upload-artifact@v4
        with:
          name: azure-resources-zip
          path: azure-resources.zip
